language: java
jdk: openjdk11
env:
    - PROJECT_DIR=trie
    - PROJECT_DIR=treeset
before_install:
    - cd "$PROJECT_DIR"
script:
    - ./gradlew check && ./gradlew javadoc
after_success:
    - cd .. && bash .travis/deploy_to_pages.sh
